version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Jocar_db
      - POSTGRES_USER=Jocar
      - POSTGRES_PASSWORD=Jocar_pswd
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=Jocar_db
      - POSTGRES_USER=Jocar
      - POSTGRES_PASSWORD=Jocar_pswd
    depends_on:
      - db