# Generated by Django 4.0.4 on 2022-05-26 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=99, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'car',
                'verbose_name_plural': 'cars',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obyom', models.CharField(max_length=99, null=True)),
                ('moshnost', models.CharField(max_length=99, null=True)),
                ('korobka', models.CharField(max_length=99, null=True)),
                ('dvigatel', models.CharField(max_length=99, null=True)),
                ('toplivo', models.CharField(max_length=99, null=True)),
                ('privod', models.CharField(max_length=99, null=True)),
                ('razgon', models.CharField(max_length=99, null=True)),
                ('rasxod', models.CharField(max_length=99, null=True)),
                ('max_skorost', models.CharField(max_length=99, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.cars')),
            ],
            options={
                'verbose_name': 'car',
                'verbose_name_plural': 'cars',
            },
        ),
    ]
