# Generated by Django 4.0.4 on 2022-05-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'car_spetification', 'verbose_name_plural': 'cars_spetifications'},
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='car',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='image',
            field=models.FileField(null=True, upload_to='cars_image'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='model',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
