# Generated by Django 4.0.4 on 2022-05-27 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carmodel_options_remove_carmodel_car_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='obyom',
            new_name='obyom2',
        ),
    ]
