# Generated by Django 4.0.4 on 2022-05-27 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_obyom_carmodel_obyom2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='moshnost',
            new_name='moshnost2',
        ),
    ]
