# Generated by Django 4.0.4 on 2022-06-03 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_moshnost_carmodel_moshnost2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='dvigatel',
            new_name='consumption',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='korobka',
            new_name='drive_unit',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='max_skorost',
            new_name='engine',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='moshnost2',
            new_name='fuel',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='obyom2',
            new_name='max_speed',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='privod',
            new_name='overclocking',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='rasxod',
            new_name='power',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='razgon',
            new_name='transmission',
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='toplivo',
            new_name='volume',
        ),
    ]
